language: cpp
compiler: gcc
dist: xenial

addons:
  apt:
    packages:
      cmake
      libzmq3-dev
      libjsoncpp-dev
      libmodbus-dev
      doxygen
      graphviz
      python-pip

install:
  - pip install --user gcovr

script:
  - make -j
  - make -j test
  - make doxygen

deploy:
  provider: pages
  repo: jconstam/ZeroMBQDocs
  skip_cleanup: true
  github_token: $GITHUB_API_KEY
  keep_history: true
  local_dir: build/doxygen/html
  on:
    branch: master
      
