language: cpp
compiler: gcc
dist: xenial

addons:
  apt:
    packages:
      cmake
      libzmq3-dev
      libjsoncpp-dev
      doxygen
      graphviz

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: make -j test
    - stage: build
      name: "Build Binary"
      script: make -j
      