language: cpp
compiler: gcc
dist: xenial

addons:
  apt:
    packages:
      cmake
      libzmq3-dev
      libjsoncpp-dev
      doxygen
      graphviz

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: make -j unittests
    - stage: build
      name: "Build Binary"
      script: make -j

after_success:
  cd scripts && ./automerge.sh $USERNAME $PASSWORD