language: cpp
compiler: gcc
dist: xenial

before_install:
  - sudo pip install gcovr

addons:
  apt:
    packages:
      cmake
      libzmq3-dev
      libjsoncpp-dev
      libmodbus-dev
      doxygen
      graphviz
      python-pip

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: make -j unittests
    - stage: build
      name: "Build Binary"
      script: make -j
      